
on:
  - push

name: CI

jobs:
  nexus-build-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - uses: guzzlehttp/guzzle@v7.3

      - name: PHPUnit Nexus tests
        uses: phpunit/phpunit@v9.5.4
        env:
          TEST_NAME: Gizmo
        with:
          bootstrap: test/bootstrap.php
          configuration: test/phpunit.xml
          args: --colors --testsuite "nexus"

  portal-build-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - uses: guzzlehttp/guzzle@v7.3

      - name: PHPUnit Portal tests
        uses: phpunit/phpunit@v9.5.4
        env:
          TEST_NAME: Stripe
        with:
          bootstrap: test/bootstrap.php
          configuration: test/phpunit.xml
          args: --colors --testsuite "leaf"