name: PHPUnit

on: [push]
  push:
    branches:
      - master
      - preprod
      - dev
jobs:
  build-test:
    name: Build Tests
    runs-on: ubuntu-latest
    steps:
      name: PHPUnit Tests
      uses: actions/checkout@v2, php-actions/composer@v5, guzzlehttp/guzzle@7.3, phpunit/phpunit@9.5.4
        env:
          TEST_NAME: Gizmo
        with:
          bootstrap: test/bootstrap.php
          configuration: test/phpunit.xml